#! /usr/bin/python3 

print("Change_IP_Service")
print("base on Flask to change server ip")
print()
print("Use Get Method To Show Web")
print("------------------------------")
print("URL: 127.0.0.1:5000")
print("------------------------------")
print("Now Service IP : XXX.XXX.XXX.XXX")
print("------------------------------")
print("Service Status :")
print("Monitor_Service  : XXX | Status : ON / OFF | Button : Start & Restart")
print("DataBase_Service : XXX | Status : ON / OFF | Button : Start & Restart")
print("------------------------------")
print("Renew IP : XXX.XXX.XXX.XXX | Button : Submit")
print("------------------------------")
print()
print("Use Post Method Recive Data")
print("------------------------------")
print("Change Librenms Container IP For Users Input !")
print("------------------------------")
