{
 "title": "LibreNMS-cloud-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "DataBases",
    "query": "show databases LIKE 'school_____';"
   },
   {
    "name": "Devices",
    "query": "select sysName from $DataBases.devices;"
   }
  ]
 },
 "panels": [
  {
   "title": "設備管理 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hostname\nFROM $DataBases.devices\nWHERE\n  $DataBases.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備廠商",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  os\nFROM $DataBases.devices\nWHERE\n  $DataBases.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備分類",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  type  \nFROM $DataBases.devices\nWHERE\n  $DataBases.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  status\nFROM $DataBases.devices\nWHERE\n  $DataBases.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備註釋",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  sysDescr\nFROM $DataBases.devices\nWHERE\n  $DataBases.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  a.timestamp AS \"time\",\n  a.max,\n  a.min\nFROM $DataBases.device_perf a, $DataBases.devices b\nWHERE\n  a.device_id = b.device_id AND\n  b.sysName = '$Devices'\nORDER BY a.timestamp"
    }
   ]
  },
  {
   "title": "學校設備總列表",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT sysName AS Device,\n       status AS Status,\n       (CASE WHEN status = 0 THEN 'N/A' ELSE uptime END) AS Uptime \nFROM $DataBases.devices"
    }
   ]
  },
  {
   "title": "系統設備使用率列表",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 6, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  $DataBases.device_perf.device_id,\n  $DataBases.device_perf.max,\n  $DataBases.device_perf.avg,\n  $DataBases.device_perf.min\nFROM $DataBases.device_perf, $DataBases.devices\nWHERE\n  $DataBases.devices.device_id = $DataBases.device_perf.device_id\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Alert Log",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT b.sysName,\n       a.details, a.state,\n       a.time_logged\nFROM $DataBases.alert_log a, $DataBases.devices b\nWHERE a.device_id = b.device_id\nORDER BY a.time_logged DESC"
    }
   ]
  }
 ]
}