{
 "title": "LibreNMS-Cloud-DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DataBases",
    "query": "SELECT school_Name FROM information_schema.schemata, school_monitor_system.edge_list where schema_name like 'school_______' and schema_name = concat('school_', school_Id); "
   },
   {
    "name": "DataBase_Name",
    "query": "select concat('school_', school_Id) from school_monitor_system.edge_list where school_Name = '$DataBases';"
   },
   {
    "name": "Devices",
    "query": "select sysName from $DataBase_Name.devices;"
   },
   {
    "name": "Device_Count",
    "query": "select count(*) from $DataBase_Name.devices;"
   }
  ]
 },
 "panels": [
  { "title": "現在時間", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "學校縣市",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Location\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "國教署-學校總稱",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Name\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "Librenms 狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(upper(LEFT(School_Status,1)), SUBSTRING(School_Status, 2, length(School_Status)-1))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 Librenms 樹莓派 MAC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  upper(School_MAC)\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 對外 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  School_IP\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 最後更新狀態時間",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(LEFT(School_LastCheck, 10), '\\n', SUBSTRING(School_LastCheck, 11))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "設備管理 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hostname\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備廠商",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(replace(icon, '.svg', ''),1)), SUBSTRING(replace(icon, '.svg', ''), 2, length(replace(icon, '.svg', ''))-1))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備分類",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(type,1)), SUBSTRING(type, 2, length(type)-1))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  status\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備註釋",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  sysDescr\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備負載狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.timestamp, INTERVAL 8 HOUR) AS \"time\",\n  a.max,\n  a.min,\n  a.avg\nFROM $DataBase_Name.device_perf a, $DataBase_Name.devices b\nWHERE\n  a.device_id = b.device_id AND\n  b.sysName = '$Devices'\nORDER BY a.timestamp"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.time_logged, INTERVAL 8 hour) AS \"time_sec\",\n  a.status\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\nORDER BY a.time_logged"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"最後更新時間\",\n  if(a.status = 1, \"開機中\", \"關機\") AS \"目前狀態\"\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\ngroup by id desc limit 20"
    }
   ]
  },
  {
   "title": "學校設備總列表(測試用)",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT a.sysName AS Device,\r\n       a.status AS Status,\r\n       (CASE WHEN a.status = 0 THEN 'N/A' ELSE uptime END) AS Uptime,\r\n       b.timestamp AS \"Latest Update Time\",\r\n       b.max,\r\n       b.min,\r\n       b.avg\r\nFROM $DataBase_Name.devices a, $DataBase_Name.device_perf b\r\nWHERE a.device_id = b.device_id\r\nORDER BY b.timestamp desc limit $Device_Count\r\n"
    }
   ]
  },
  {
   "title": "Alert Log",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT b.sysName,\n       a.details, \n       a.state,\n       a.time_logged as \"alert_time\"\nFROM $DataBase_Name.alert_log a, $DataBase_Name.devices b\nWHERE a.device_id = b.device_id\nORDER BY alert_time desc"
    }
   ]
  },
  {
   "title": "學校設備總列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT sysName AS Device,\n       status AS Status,\n       (CASE WHEN status = 0 THEN 'N/A' ELSE uptime END) AS Uptime \nFROM $DataBases.devices"
    }
   ]
  },
  {
   "title": "系統設備使用率列表",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  $DataBases.device_perf.device_id as \"sysName\",\n  $DataBases.device_perf.max,\n  $DataBases.device_perf.avg,\n  $DataBases.device_perf.min\nFROM $DataBases.device_perf, $DataBases.devices\nWHERE\n  $DataBases.devices.device_id = $DataBases.device_perf.device_id \nORDER BY timestamp"
    }
   ]
  }
 ]
}