{
 "title": "LibreNMS-Cloud-DashBoard-(2020/05/07)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DataBases",
    "query": "SELECT school_Name FROM information_schema.schemata, school_monitor_system.edge_list where schema_name like 'school_______' and schema_name = concat('school_', school_Id); "
   },
   {
    "name": "DataBase_Name",
    "query": "select concat('school_', school_Id) from school_monitor_system.edge_list where school_Name = '$DataBases';"
   },
   {
    "name": "Devices",
    "query": "select sysName from $DataBase_Name.devices;"
   },
   {
    "name": "Device_Count",
    "query": "select count(*) from $DataBase_Name.devices;"
   },
   {
    "name": "Device_Hostname",
    "query": "select hostname from $DataBase_Name.devices where sysName = '$Devices';"
   },
   {
    "name": "Device_Ports",
    "query": "select  port_name from  $DataBase_Name.ports where hostname = '$Device_Hostname'"
   },
   {
    "name": "Device_Ports_Count",
    "query": "select  count(distinct(port_name)) from  $DataBase_Name.ports where hostname = '$Device_Hostname'"
   }
  ]
 },
 "panels": [
  { "title": "現在時間", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "學校縣市",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Location\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "國教署-學校總稱",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Name\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "Librenms 狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(upper(LEFT(School_Status,1)), SUBSTRING(School_Status, 2, length(School_Status)-1))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 Librenms 樹莓派 MAC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  upper(School_MAC)\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 對外 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  School_IP\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 最後更新狀態時間",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(LEFT(School_LastCheck, 10), '\\n', SUBSTRING(School_LastCheck, 11))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "SpeedTest 每日測試",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "SpeedTest Ping",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  ping\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "SpeedTest Download",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
     "format": "Mbits",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  download\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "SpeedTest Upload",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
     "format": "Mbits",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  upload\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "Server Location",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_name\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "Server Sponsor",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_sponsor\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "Server Distance",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
     "format": "lengthkm",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_distance\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "Test TimeStamp",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 19, "y": 5 },
     "format": "lengthkm",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  concat(LEFT(time_logged, 10), '\\n', SUBSTRING(time_logged, 11))\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "Cost Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  time_logged AS \"time\",\n  end_time-start_time\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
      }
     ]
    },
    {
     "title": "SpeedTest Ping History",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  ping\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
      }
     ]
    },
    {
     "title": "SpeedTest Download / Upload History",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  download AS \"下載\"\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
      },
      {
       "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  upload AS \"上傳\"\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
      }
     ]
    },
    {
     "title": "SpeedTest Use Time History",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  end_time-start_time\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
      }
     ]
    }
   ]
  },
  {
   "title": "設備即時狀態",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "設備管理 IP",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hostname\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    },
    {
     "title": "設備廠商",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(os,1)), SUBSTRING(os, 2, length(os)))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    },
    {
     "title": "設備名稱",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  sysName\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    },
    {
     "title": "設備分類",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(type,1)), SUBSTRING(type, 2, length(type)-1))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    },
    {
     "title": "設備狀態",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  status\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    },
    {
     "title": "設備註釋",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
     "format": "none",
     "valueName": "first",
     "targets": [
      {
       "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  sysDescr\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
      }
     ]
    }
   ]
  },
  {
   "title": "學校設備狀態總覽",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "學校設備總列表(測試用)",
     "type": "table",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT a.hostname AS \"設備網管IP\",\r\n       concat(upper(LEFT(a.os,1)), SUBSTRING(a.os, 2, length(a.os))) AS \"設備廠商\",\r\n       a.sysName AS \"設備名稱\",\r\n       if (a.status=1, \"開機中\", \"關機\") AS \"設備狀態\",\r\n       b.timestamp AS \"最後更新時間\",\r\n       b.max AS \"最大負載\",\r\n       b.min AS \"最小負載\",\r\n       b.avg AS \"平均負載\"\r\nFROM $DataBase_Name.devices a, $DataBase_Name.device_perf b\r\nWHERE a.device_id = b.device_id\r\nORDER BY b.timestamp desc limit $Device_Count"
      }
     ]
    },
    {
     "title": "Alert Log",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT b.sysName,\n       a.details, \n       a.state,\n       a.time_logged as \"alert_time\"\nFROM $DataBase_Name.alert_log a, $DataBase_Name.devices b\nWHERE a.device_id = b.device_id\nORDER BY alert_time desc"
      }
     ]
    }
   ]
  },
  { "title": "設備歷史圖表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "設備負載狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.timestamp, INTERVAL 8 HOUR) AS \"time\",\n  a.max,\n  a.min,\n  a.avg\nFROM $DataBase_Name.device_perf a, $DataBase_Name.devices b\nWHERE\n  a.device_id = b.device_id AND\n  b.sysName = '$Devices'\nORDER BY a.timestamp"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.time_logged, INTERVAL 8 hour) AS \"time_sec\",\n  a.status\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\nORDER BY a.time_logged"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"最後更新時間\",\n  if(a.status = 1, \"開機中\", \"關機\") AS \"目前狀態\"\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\ngroup by id desc limit 20"
    }
   ]
  },
  { "title": "網路設備連接埠資訊", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "設備管理 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hostname\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "網路設備埠口流量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  input AS \"流入\",\n  output AS \"流出\"\nFROM $DataBase_Name.ports\nWHERE\n  port_name = '$Device_Ports' AND\n  hostname = '$Device_Hostname'\nORDER BY time_logged"
    }
   ]
  },
  {
   "title": "網路設備埠口流量",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  IF(port_status=\"up\", 1, 0) as \"狀態\",\n  input AS \"流入\",\n  input AS \"流出\"\nFROM $DataBase_Name.ports\nWHERE port_name = '$Device_Ports' and hostname = '$Device_Hostname'\nORDER BY time_logged\nlimit 20"
    }
   ]
  },
  {
   "title": "網路設備埠口名稱",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  port_name\nFROM $DataBase_Name.ports\nWHERE\n  port_name = '$Device_Ports' and hostname = '$Device_Hostname'\nORDER BY time_logged desc\nlimit 1"
    }
   ]
  },
  {
   "title": "網路設備埠口硬體速度",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  port_speed\nFROM $DataBase_Name.ports\nWHERE\n  port_name = '$Device_Ports' and hostname = '$Device_Hostname'\nORDER BY time_logged desc\nlimit 1"
    }
   ]
  },
  {
   "title": "網路設備埠口連接狀態",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  IF(port_status=\"up\", 1, 0) as \"執行狀態\"\nFROM $DataBase_Name.ports\nWHERE port_name = '$Device_Ports' and hostname = '$Device_Hostname'\nORDER BY time_logged"
    }
   ]
  },
  {
   "title": "網路設備埠口連接狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  IF(port_status=\"up\", 1, 0)\nFROM $DataBase_Name.ports\nWHERE port_name = '$Device_Ports' and hostname = '$Device_Hostname'\nORDER BY time_logged desc\nlimit 1"
    }
   ]
  },
  { "title": "設備網路埠口總覽", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "網路設備埠口流量總覽  (流入)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 19, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select a.port_name as \"埠口名稱\", a.input as \"流入\", DATE_ADD(a.time_logged, Interval 8 hour) as \"time\"\nfrom (select port_name, input, time_logged from $DataBase_Name.ports where hostname = '$Device_Hostname') as a, (SELECT port_name, max(time_logged) as \"time_logged\" FROM $DataBase_Name.ports WHERE hostname = '$Device_Hostname' GROUP BY port_name) as b \nwhere a.port_name=b.port_name and a.time_logged=b.time_logged\norder by a.input desc;"
    }
   ]
  },
  {
   "title": "網路設備埠口流量總覽",
   "type": "table",
   "gridPos": { "h": 35, "w": 5, "x": 19, "y": 34 },
   "targets": [
    {
     "rawSql": "select a.port_name as \"埠口名稱\", if(a.port_status=\"up\", 1, 0) as \"狀態\", DATE_ADD(a.time_logged, Interval 8 hour) as \"最後更新時間戳記\"\nfrom (select port_name, port_status, time_logged from $DataBase_Name.ports where hostname = '$Device_Hostname') as a, (SELECT port_name, max(time_logged) as \"time_logged\" FROM $DataBase_Name.ports WHERE hostname = '$Device_Hostname' GROUP BY port_name) as b \nwhere a.port_name=b.port_name and a.time_logged=b.time_logged"
    }
   ]
  },
  {
   "title": "網路設備埠口流量總覽 (流出)",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "select a.port_name as \"埠口名稱\", a.output as \"流出\", DATE_ADD(a.time_logged, Interval 8 hour) as \"time\"\nfrom (select port_name, output, time_logged from $DataBase_Name.ports where hostname = '$Device_Hostname') as a, (SELECT port_name, max(time_logged) as \"time_logged\" FROM $DataBase_Name.ports WHERE hostname = '$Device_Hostname' GROUP BY port_name) as b \nwhere a.port_name=b.port_name and a.time_logged=b.time_logged\norder by a.output desc;"
    }
   ]
  },
  {
   "title": "已連接設備的網路設備埠口流量總覽",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(port_name) AS \"埠口名稱\",\n  input AS \"流入\",\n  output AS \"流出\",\n  time_logged AS \"time\"\nFROM $DataBase_Name.ports\nWHERE hostname = '$Device_Hostname' and (output > 0 or input > 0)"
    }
   ]
  }
 ]
}