{
 "title": "LibreNMS-Cloud-DashBoard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DataBases",
    "query": "SELECT school_Name FROM information_schema.schemata, school_monitor_system.edge_list where schema_name like 'school_______' and schema_name = concat('school_', school_Id); "
   },
   {
    "name": "DataBase_Name",
    "query": "select concat('school_', school_Id) from school_monitor_system.edge_list where school_Name = '$DataBases';"
   },
   {
    "name": "Devices",
    "query": "select sysName from $DataBase_Name.devices;"
   },
   {
    "name": "Device_Count",
    "query": "select count(*) from $DataBase_Name.devices;"
   }
  ]
 },
 "panels": [
  { "title": "現在時間", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "學校縣市",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Location\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "國教署-學校總稱",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_Serial_Id AS \"time\",\n  School_Name\nFROM school_monitor_system.edge_list\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_Serial_Id"
    }
   ]
  },
  {
   "title": "Librenms 狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(upper(LEFT(School_Status,1)), SUBSTRING(School_Status, 2, length(School_Status)-1))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 Librenms 樹莓派 MAC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  upper(School_MAC)\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 對外 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  School_IP\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  {
   "title": "學校端 最後更新狀態時間",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  School_LastCheck AS \"time\",\n  concat(LEFT(School_LastCheck, 10), '\\n', SUBSTRING(School_LastCheck, 11))\nFROM school_monitor_system.edge_regist\nWHERE\n  concat('school_', school_Id) = '$DataBase_Name'\nORDER BY School_LastCheck"
    }
   ]
  },
  { "title": "SpeedTest 每日測試", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SpeedTest Ping",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  ping\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "SpeedTest Download",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  download\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "SpeedTest Upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  upload\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "Server Location",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_name\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "Server Sponsor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_sponsor\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "Server Distance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 5 },
   "format": "lengthkm",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  server_distance\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "Test TimeStamp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 5 },
   "format": "lengthkm",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  concat(LEFT(time_logged, 10), '\\n', SUBSTRING(time_logged, 11))\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "Cost Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"time\",\n  end_time-start_time\nFROM $DataBase_Name.speedtest\nORDER BY id\ndesc\nlimit 1"
    }
   ]
  },
  {
   "title": "SpeedTest Ping History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  ping\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
    }
   ]
  },
  {
   "title": "SpeedTest Download / Upload History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  download AS \"下載\"\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
    },
    {
     "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  upload AS \"上傳\"\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
    }
   ]
  },
  {
   "title": "SpeedTest Use Time History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(time_logged, INTERVAL 8 HOUR) AS \"time\",\n  end_time-start_time\nFROM $DataBase_Name.speedtest\nORDER BY id\n"
    }
   ]
  },
  { "title": "學校設備狀態總覽", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "學校設備總列表(測試用)",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT a.sysName AS Device,\r\n       a.status AS Status,\r\n       (CASE WHEN a.status = 0 THEN 'N/A' ELSE uptime END) AS Uptime,\r\n       b.timestamp AS \"Latest Update Time\",\r\n       b.max,\r\n       b.min,\r\n       b.avg\r\nFROM $DataBase_Name.devices a, $DataBase_Name.device_perf b\r\nWHERE a.device_id = b.device_id\r\nORDER BY b.timestamp desc limit $Device_Count\r\n"
    }
   ]
  },
  {
   "title": "Alert Log",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT b.sysName,\n       a.details, \n       a.state,\n       a.time_logged as \"alert_time\"\nFROM $DataBase_Name.alert_log a, $DataBase_Name.devices b\nWHERE a.device_id = b.device_id\nORDER BY alert_time desc"
    }
   ]
  },
  { "title": "設備即時狀態", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "設備管理 IP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hostname\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備廠商",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(icon,1)), SUBSTRING(icon, 2, length(icon)-5))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備名稱",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  hardware\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備分類",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  concat(upper(LEFT(type,1)), SUBSTRING(type, 2, length(type)-1))\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備狀態",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  status\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  {
   "title": "設備註釋",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  agent_uptime AS \"time\",\n  sysDescr\nFROM $DataBase_Name.devices\nWHERE\n  $DataBase_Name.devices.sysName = '$Devices'\nORDER BY agent_uptime"
    }
   ]
  },
  { "title": "設備歷史圖表", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "設備負載狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.timestamp, INTERVAL 8 HOUR) AS \"time\",\n  a.max,\n  a.min,\n  a.avg\nFROM $DataBase_Name.device_perf a, $DataBase_Name.devices b\nWHERE\n  a.device_id = b.device_id AND\n  b.sysName = '$Devices'\nORDER BY a.timestamp"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_SUB(a.time_logged, INTERVAL 8 hour) AS \"time_sec\",\n  a.status\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\nORDER BY a.time_logged"
    }
   ]
  },
  {
   "title": "設備開關歷史狀態",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_logged AS \"最後更新時間\",\n  if(a.status = 1, \"開機中\", \"關機\") AS \"目前狀態\"\nFROM $DataBase_Name.device_state_history a, $DataBase_Name.devices b\nwhere a.device_id = b.device_id and b.sysName = '$Devices'\ngroup by id desc limit 20"
    }
   ]
  }
 ]
}